console.log('NODE_ENV', process.env.NODE_ENV)
console.log('BRANCH', process.env.BRANCH)
console.log('CONTEXT', process.env.CONTEXT)
console.log('NODE_VERSION', process.env.NODE_VERSION)
console.log('NPM_VERSION', process.env.NPM_VERSION)
console.log('REPOSITORY_URL', process.env.REPOSITORY_URL)
console.log('ACCESS_TOKEN', process.env.ACCESS_TOKEN)