[build]
  publish = "dist"
  command = "npm run build"
  environment = {  NODE_VERSION = "8.11.3" }
[context.production]
  environment = { ACCESS_TOKEN = "******123" }
[context.develop]
  environment = { ACCESS_TOKEN = "******456", NODE_ENV = "development" }