[build]
  publish = "dist"
  command = "npm run build"
  NODE_VERSION = "8.11.3"
[context.production]
  environment = { ACCESS_TOKEN = "******123"}
[context.develop]
  environment = { ACCESS_TOKEN = "******456"}